apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsdvda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fsdvda
  template:
    metadata:
      labels:
        app: fsdvda
    spec:
      containers:
      - image: okteto.dev/fsdvda:latest
        name: fsdvda
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e15f2bb8-cbb8-444a-8a57-baeee7dee2f8"
        - name: Vless_Path
          value: "/vlfsg555"
        - name: Vmess_UUID
          value: "e15f2bb8-cbb8-444a-8a57-baeee7dee2f8"
        - name: Vmess_Path
          value: "/vmgghr666"
        - name: Share_Path
          value: "/v2link"
